[tool.black]
line-length = 90
fast = true

[tool.coverage.run]
branch = true
omit = [
    "*/tests/*",
]

[tool.coverage.report]
fail_under = 95
skip_empty = true
show_missing = true

[tool.pylint.main]
max-line-length = 90

[tool.isort]
float_to_top=true
