#!/bin/sh

# Get the current branch name
branch=$(git symbolic-ref --short HEAD)

# Prevent commits to main branch
if [ "$branch" = "main" ]; then
  echo "You cannot commit directly to the 'main' branch."
  exit 1
fi
